version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_PASSWORD: root
    networks:
      - defaultnet
    ports:
      - "3308:3306"

  dcmysql-art:
    container_name: dcmysql-art
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=art
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - defaultnet
    restart: always

  discovery:
    image: consul:1.7
    networks:
      - defaultnet
    ports:
      - 8500:8500

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
    networks:
      - defaultnet
    ports:
      - 8000:8080
    depends_on:
      - mysql
      - discovery

  art-service:
    image: art-microservices/art-service
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DMYSQL_HOST=dcmysql-art
        -DMYSQL_PORT=3306
        -DKEYCLOAK_HOST=keycloak
        -DKEYCLOAK_PORT=8080
      #- SPRING_DATASOURCE_URL=jdbc:mysql://dcmysql-art:3306/art?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - defaultnet
    depends_on:
      - dcmysql-art
      - discovery

  keycloak-service:
    image: art-microservices/keycloak-service
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DKEYCLOAK_HOST=keycloak
        -DKEYCLOAK_PORT=8080
    networks:
      - defaultnet
    depends_on:
      - keycloak
      - discovery
    ports:
      - 5555:5555

  dc-mongodb:
    build: mongo/
    container_name: mongodb
    environment:

      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: review
    networks:
      - defaultnet
    ports:
      - 27017:27017

  review-service:
    image: art-microservices/review-service
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
        -DMONGODB_HOST=mongodb
        -DMONGODB_PORT=27017
        -DKEYCLOAK_HOST=keycloak
        -DKEYCLOAK_PORT=8080

    networks:
      - defaultnet
    depends_on:
      - discovery
      - dc-mongodb

  gateway:
    image: art-microservices/gateway
    ports:
      - 8089:8089
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    networks:
      - defaultnet
    depends_on:
      - discovery

networks:
  defaultnet:
