# Derived from official mongo image (our base image)
FROM mongo:latest


# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
#COPY ./mongo_script/ /docker-entrypoint-initdb.d/
